name: Build Check

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  check:
    strategy:
      matrix:
        os: [ macos-12, windows-2022 ]
    runs-on: ${{ matrix.os }}
    env:
      GRADLE_VERSION: 7.6
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: 17

      - name: Setup and performs Gradle 'check' task.
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
          arguments: check
