name: Build Check

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  check:
    name: '${{ matrix.os }} - java/${{ matrix.java }}-zulu & gradle v${{ matrix.gradle }}'
    strategy:
      matrix:
        os: [ macos-12, windows-2022, ubuntu-22.04 ]
        java: [ '11.0.18', '17.0.6' ]
        gradle: [ '7.5', '7.5.1', '7.6' ]
    runs-on: ${{ matrix.os }}
    env:
      GRADLE_VERSION: ${{ matrix.gradle }}
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}

      - name: Setup and performs Gradle 'check' task.
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6
          arguments: check
