name: SonarQube

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  analysis-1:
    name: '${{ matrix.os }} - v${{ matrix.gradle }} & ${{ matrix.java }}-zulu'
    strategy:
      matrix:
        os: [ macos-12, windows-2022 ]
        java: [ '11.0.18', '17.0.6' ]
        gradle: [ '7.5', '7.5.1', '7.6' ]
    runs-on: ${{ matrix.os }}
    environment: SonarQube
    env:
      GRADLE_VERSION: ${{ matrix.gradle }}
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Performs 'check' task.
        uses: gradle/gradle-build-action@v2
        env:
          org.gradle.project.sonarqube.project.key: argo-${{ runner.os }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          gradle-version: 7.6
          cache-disabled: false
          arguments: |
            check
            --stacktrace
            --continue
            --build-cache
            --scan

      - name: Reports upload
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}--${{ matrix.java }}--${{ matrix.gradle }}--build
          path: '**/build/reports/'
  analysis-2:
    name: 'Ubuntu'
    runs-on: ubuntu-22.04
    environment: SonarQube
    env:
      GRADLE_VERSION: 7.6
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: '17.0.6'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Performs 'check' task.
        uses: gradle/gradle-build-action@v2
        env:
          org.gradle.project.sonarqube.project.key: argo-${{ runner.os }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          gradle-version: 7.6
          cache-disabled: false
          arguments: |
            check
            --stacktrace
            --continue
            --build-cache
            --scan

      - name: Reports upload
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}--17.0.6--7.6--build
          path: '**/build/reports/'
