name: Compatibility

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  compatibility:
    name: '${{ matrix.os }}(${{ matrix.java }}-zulu, v${{ matrix.gradle }})'
    timeout-minutes: 60
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-12, windows-2022 ]
        java: [ '17.0.6', '19.0.2' ]
        gradle: [ '7.6', '8.0.2' ]
    runs-on: ${{ matrix.os }}
    env:
      GRADLE_VERSION: ${{ matrix.gradle }}
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}

      - name: Performs 'check' task.
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.0.2'
          cache-disabled: false
          arguments: |
            check
            --stacktrace
            --continue
            --build-cache
            --scan

      - name: Upload 'build-report'
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}--${{ matrix.java }}--${{ matrix.gradle }}--build-report
          path: '**/build/reports/'
