name: Compatibility

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  compatibility-1:
    name: '${{ matrix.os }} - v${{ matrix.gradle }} & ${{ matrix.java }}-zulu'
    strategy:
      matrix:
        os: [ macos-12, windows-2022 ]
        java: [ '11.0.18', '17.0.6' ]
        gradle: [ '7.5', '7.5.1', '7.6' ]
    runs-on: ${{ matrix.os }}
    env:
      GRADLE_VERSION: ${{ matrix.gradle }}
    if: ${{ !contains(github.event.head_commit.message, 'ci compatibility-skip') }}
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}

      - name: Performs 'check' task.
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6
          cache-disabled: false
          arguments: |
            check
            --stacktrace
            --continue
            --build-cache
            --scan

      - name: Reports upload
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}--${{ matrix.java }}--${{ matrix.gradle }}--build-report
          path: '**/build/reports/'

  compatibility-2:
    name: 'Ubuntu'
    runs-on: ubuntu-22.04
    environment: SonarQube
    env:
      GRADLE_VERSION: 7.6
    if: ${{ !contains(github.event.head_commit.message, 'ci compatibility-skip') }}
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: '17.0.6'

      - name: Performs 'check' task.
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6
          cache-disabled: false
          arguments: |
            check
            --stacktrace
            --continue
            --build-cache
            --scan

      - name: Build Report upload
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-22.04--17.0.6--7.6--build-report
          path: '**/build/reports/'
