name: Gradle
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  validation:
    name: 'Wrapper validation'
    runs-on: ubuntu-22.04
    steps:

      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      
