name: Publication

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish:
    name: 'argo'
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    environment: Portal
    env:
      ORG_GRADLE_PROJECT_gradle.publish.key: ${{ secrets.GRADLE_PUBLISH_KEY }}
      ORG_GRADLE_PROJECT_gradle.publish.secret: ${{ secrets.GRADLE_PUBLISH_PASSWORD }}
      ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_PK }}
      ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17.0.6

      - name: Performs 'publish-plugin' task.
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish-plugin
