name: Publish

on:
  push:
    branches:
      - 'main'

jobs:
  publish:
    name: 'Argo'
    runs-on: ubuntu-22.04
    environment: Portal
    env:
      gradle.publish.key: ${{ secrets.GRADLE_PUBLISH_KEY }}
      gradle.publish.secret: ${{ secrets.GRADLE_PUBLISH_PASSWORD }}
      org.gradle.project.signing.key: ${{ secrets.SIGNING_PK }}
      org.gradle.project.signing.password: ${{ secrets.SIGNING_PASSWORD }}
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: 17

      - name: Performs 'publish' task.
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
