name: Publish Plugin to Gradle Plugin Portal

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v0.*'

jobs:
  publish:
    name: 'Argo Publication'
    runs-on: ubuntu-22.04
    environment: Main
    env:
      gradle.publish.key: ${{ secrets.GRADLE_PUBLISH_KEY }}
      gradle.publish.secret: ${{ secrets.GRADLE_PUBLISH_SECRET }}
      org.gradle.project.signing.key: ${{ secrets.ORG_GRADLE_PROJECT_SIGNING_KEY }}
      org.gradle.project.signing.password: ${{ secrets.ORG_GRADLE_PROJECT_SIGNING_PASSWORD }}
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: 17

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
