name: Publish Plugin to Gradle Plugin Portal

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v1.*'

jobs:
  gradle:
    runs-on: ubuntu-latest
    env:
      gradle.publish.key: ${{ secrets.GRADLE_PUBLISH_KEY }}
      gradle.publish.secret: ${{ secrets.GRADLE_PUBLISH_SECRET }}
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: check

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
