name: Sign

on:
  pull_request:
    branches:
      - '*'

jobs:
  sign:
    name: Signing
    runs-on: ubuntu-22.04
    environment: Portal
    env:
      gradle.publish.key: ${{ secrets.GRADLE_PUBLISH_KEY }}
      gradle.publish.secret: ${{ secrets.GRADLE_PUBLISH_PASSWORD }}
      ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_PK }}
      ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17.0.6

      - name: Performs 'sign' task.
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ':argo-plugin:signArgoPluginPluginMarkerMavenPublication'
